# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffffb772b56c1efb54667fb7451cf57d3d85ffab79d9b975552851fdebe8129fd53b29a87432393a714d1f652c6b919021cfabbc66d2e0d9f278ebd7cd5a1fd9

test:
  secret_key_base: 0be4ae3ccdb8a5195b2fc8ee9033eda16f369a22b666108b9e61b4c540f04ae87906a0f735bce9918b21f7c4390d52fb69af56ac211912eb4dcb72261609fd60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
